### PR TITLE
set number

### PR DESCRIPTION
**Pull request by snkemp**
This is a great vimrc, I was very surprised that there were no line numbers (easy fix) I added it under general.

### CODE REVIEW

**Comment by zhaozhiming** [comment]
duplicate of issue #219

**Comment by alphaCTzo7G** [comment]
I think the previous one was closed. I would think this is a very common requirement, so should be put as a default in basic.vim?

I use `set relative number` and `set nu`, but atleast we should have `set number` in the basic.vim so everybody who uses this vimrc has access to that without having to figure out the commands to enable that.

**Comment by amix** [comment]
You have the line-number bottom-right.

Personally, I want to focus on the code/text and not on line-numbers. This is why the default disables it.

**Comment by alphaCTzo7G** [comment]
Ahh ok.. The line numbers primarily help me in move up and down. For example when I use relative numbers, and I want to move 12 lines up, the line number difference from the current cursor location to the final location is visible on the screen. So I can do a 12k, to go the other line.

If on the other hand, the line numbers are not visible, then I would have to calculate the difference between the line I want to move to and the current line and then use 12k.

You can also use absolute line numbers. However, if you have relatively large files (say 500 lines of code), then you would have to type `342G`. Further, you never really move that far away from where you are currently located, and most movements are within the visible screen region. So using `12j/k` is easier than `342G`. 

You can also do this while deleting or modifying or any other command which requires a `motion` such as `d12j`.

If I did have to move large distances, such as when deleting large blocks to text, I think its better to use marks to mark a certain position such as `ma`, go to the new position, and the do `d'a`, rather than using `d342G`.

is there a better way to do this? Or do you turn on line numbers manually when you have to move around your code or use `motion`?

**Comment by thouger** [comment]
> 

same point,If the number of lines is not displayed, how can I jump more conveniently?

**Comment by jnhong** [comment]
+1, line numbers are necessary for range commands

**Pull request closed without merging**
