### PR TITLE
Show line number

### PR DESCRIPTION
**Pull request by flyafly**
I think it is important to show line number,so i add "set number",thank you

### CODE REVIEW

**Comment by amix** [comment]
Feature, not a bug ;) You can see line number in bottom left

**Comment by zippy1981** [comment]
I agree, no matter the editor I like to the the line numbers on the left hand side. Otherwise basic.vim is a great basic version

**Comment by tdwebste** [comment]
:set number
:set nonumber

I do NOT like numbers, The provide no useful information most of the time.
When I need line numbers I use the status bar and ^G are for.

I like to edit blocks.
When I want line numbers I turn them on.

You probably like to edit ranges of line numbers.
If I edited ranges of line numbers, I would probably want line numbers
turned on too. But I don't



On Thu, Apr 23, 2015 at 11:37 AM, Justin Dearing <notifications@github.com>
wrote:

> I agree, no matter the editor I like to the the line numbers on the left
> hand side. Otherwise basic.vim is a great basic version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amix/vimrc/pull/104#issuecomment-95679706>.
>



-- 
778 776 9221
778 707 4922

**Comment by zippy1981** [comment]
>You probably like to edit ranges of line numbers.

I think that sums it up. I commit a lot of vim sins. I don't touch type properly. I don't hunt and peck, and I don't need to constantly look at the keyboard, but I don't do the home row thing. I use arrows, not aswd. I use visual selection mode a lot.

It would take months of dedicated training for me to get to your level.

**Comment by tdwebste** [comment]
good point, I don't know if you noticed this, but you can place a finger on
each aswd key. This is more of a gaming thing. block, word movement is
faster, so I don't bother with aswd either.

On Thu, Apr 23, 2015 at 12:09 PM, Justin Dearing <notifications@github.com>
wrote:

> You probably like to edit ranges of line numbers.
>
> I think that sums it up. I commit a lot of vim sins. I don't touch type
> properly. I don't hunt and peck, and I don't need to constantly look at the
> keyboard, but I don't do the home row thing. I use arrows, not aswd. I use
> visual selection mode a lot.
>
> It would take months of dedicated training for me to get to your level.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amix/vimrc/pull/104#issuecomment-95688394>.
>



-- 
778 776 9221
778 707 4922

**Pull request closed without merging**
