### PR TITLE
Adds plugin vim-gitgutter

### PR DESCRIPTION
**Pull request by bric3**
This PR proposes the great [git gutter](https://github.com/airblade/vim-gitgutter) plugin. Nothing to configure it just works.

screenshot

### CODE REVIEW

**Comment by amix** [comment]
Will try it out. Will remove it if I don't like it that much :)

Amir

**Comment by bric3** [comment]
Fair enough :)

Although I do believe there's a possibility to disable it via configuration.

**Comment by ThomasRuby** [comment]
Usefull but I prefer to disable it by default, it takes some times on big files... (e.g a big .tex file for my part on my old/slow laptop) 
Maybe a tip can be to enable it according to the number of line ?

**Comment by bric3** [comment]
@ThomasRuby @amix From the main page :)

> ### To turn off vim-gitgutter by default
> 
> Add let `g:gitgutter_enabled = 0 to your ~/.vimrc`.
> 
> ### To turn off signs by default
> 
> Add let `g:gitgutter_signs = 0 to your ~/.vimrc`.
> 
> ### To turn on line highlighting by default
>
> Add let `g:gitgutter_highlight_lines = 1 to your ~/.vimrc`.

And about the threshold, on my machine 500 is ok, but I understand this can be problematic with certain hardware / software combination.

> To keep your Vim snappy, vim-gitgutter will suppress itself when a file has more than 500 changes. As soon as the number of changes falls below the limit vim-gitgutter will show the signs again. You can configure the threshold with:
>
>     let g:gitgutter_max_signs = 500  " default value

**Comment by bric3** [comment]
By the way those plugins #116 and #117 are git submodules, and I don't think they are checked out on a simple `git clone`.

**Comment by andradei** [comment]
Yeah, vim-gitgutter comes empty and consequently won't work simply from installing the `vimrc` project.

**Comment by bric3** [comment]
It seems there's something wrong with the submodules indeed, there's no `.gitmodules` file, yet github detects the submodules. I'll look into it.

**Comment by bric3** [comment]
ah, in fact @amix removed the `.gitmodules` in commit https://github.com/amix/vimrc/commit/d7752b59ae5e51961365c7217bb936fa935e80ac#diff-8903239df476d7401cf9e76af0252622

I guess I will do another pull request that should work with his system. My opinion on this is that I'd rather use submodules now that git can initialise them upon clone (`git clone --recursive https://github.com/amix/vimrc.git`)

**Comment by andradei** [comment]
That would be a great idea. This way users can update the plugins at their own pace.

**Pull request merged**
